// Tỉnh thành phố
const data1 = [{ "UrlFacet": "ba-ria-vung-tau", "Title": " Bà Rịa - Vũng Tàu", "Total": 3531 }, {
  "UrlFacet": "thua-thien-hue",
  "Title": " Thừa Thiên Huế",
  "Total": 1603
}, {
  "UrlFacet": "dak-lak",
  "Title": " Đắk Lắk",
  "Total": 2240
}, {
  "UrlFacet": "184-bui-ta-han-phuong-an-phu-quan-2-tp-ho-chi-minh",
  "Title": "184 Bùi Tá Hán, Phường An Phú, Quận 2, Tp Hồ Chí Minh",
  "Total": 1
}, {
  "UrlFacet": "45-duong-mai-chi-tho-kv-thanh-hoa-phuong-phu-thu-quan-cai-rang-can-tho",
  "Title": "45 Đường Mai Chí Thọ, Kv Thạnh Hòa, Phường Phú Thứ, Quận Cái Răng, Cần Thơ",
  "Total": 1
}, {
  "UrlFacet": "59-ho-tung-mau-phuong-ben-nghe-quan-1-tp-ho-chi-minh",
  "Title": "59 Hồ Tùng Mậu, Phường Bến Nghé, Quận 1, Tp Hồ Chí Minh",
  "Total": 1
}, {
  "UrlFacet": "74-duong-nguyen-thi-minh-khai-phuong-06-quan-3-tp-ho-chi-minh",
  "Title": "74, Đường Nguyễn Thị Minh Khai, Phường 06, Quận 3, Tp Hồ Chí Minh",
  "Total": 1
}, { "UrlFacet": "an-giang", "Title": "An Giang", "Total": 12966 }, {
  "UrlFacet": "binh-duong",
  "Title": "Bình Dương",
  "Total": 44212
}, { "UrlFacet": "binh-phuoc", "Title": "Bình Phước", "Total": 11134 }, {
  "UrlFacet": "binh-thuan",
  "Title": "Bình Thuận",
  "Total": 11317
}, { "UrlFacet": "binh-dinh", "Title": "Bình Định", "Total": 14219 }, {
  "UrlFacet": "bac-lieu",
  "Title": "Bạc Liêu",
  "Total": 5505
}, { "UrlFacet": "bac-can", "Title": "Bắc Cạn", "Total": 2323 }, {
  "UrlFacet": "bac-giang",
  "Title": "Bắc Giang",
  "Total": 11916
}, { "UrlFacet": "bac-kan", "Title": "Bắc Kạn", "Total": 233 }, {
  "UrlFacet": "bac-ninh",
  "Title": "Bắc Ninh",
  "Total": 17814
}, { "UrlFacet": "ben-tre", "Title": "Bến Tre", "Total": 8237 }, {
  "UrlFacet": "cao-bang",
  "Title": "Cao Bằng",
  "Total": 3582
}, { "UrlFacet": "chua-ro", "Title": "Chưa rõ", "Total": 61991 }, {
  "UrlFacet": "ca-mau",
  "Title": "Cà Mau",
  "Total": 10807
}, { "UrlFacet": "can-tho", "Title": "Cần Thơ", "Total": 19697 }, {
  "UrlFacet": "gia-lai",
  "Title": "Gia Lai",
  "Total": 9656
}, { "UrlFacet": "hue", "Title": "Huế", "Total": 9875 }, {
  "UrlFacet": "ha-giang",
  "Title": "Hà Giang",
  "Total": 4592
}, { "UrlFacet": "ha-nam", "Title": "Hà Nam", "Total": 7235 }, {
  "UrlFacet": "ha-noi",
  "Title": "Hà Nội",
  "Total": 282046
}, { "UrlFacet": "ha-tinh", "Title": "Hà Tĩnh", "Total": 10865 }, {
  "UrlFacet": "hoa-binh",
  "Title": "Hòa Bình",
  "Total": 6472
}, { "UrlFacet": "hung-yen", "Title": "Hưng Yên", "Total": 12376 }, {
  "UrlFacet": "hai-duong",
  "Title": "Hải Dương",
  "Total": 16881
}, { "UrlFacet": "hai-phong", "Title": "Hải Phòng", "Total": 44792 }, {
  "UrlFacet": "hau-giang",
  "Title": "Hậu Giang",
  "Total": 5597
}, { "UrlFacet": "khanh-hoa", "Title": "Khánh Hòa", "Total": 22313 }, {
  "UrlFacet": "kien-giang",
  "Title": "Kiên Giang",
  "Total": 17543
}, { "UrlFacet": "kon-tum", "Title": "Kon Tum", "Total": 4777 }, {
  "UrlFacet": "kp-binh-hoa",
  "Title": "Kp Bình Hòa",
  "Total": 1
}, { "UrlFacet": "lai-chau", "Title": "Lai Châu", "Total": 3105 }, {
  "UrlFacet": "long-an",
  "Title": "Long An",
  "Total": 18924
}, { "UrlFacet": "lao-cai", "Title": "Lào Cai", "Total": 6789 }, {
  "UrlFacet": "lam-dong",
  "Title": "Lâm Đồng",
  "Total": 15509
}, { "UrlFacet": "lang-son", "Title": "Lạng Sơn", "Total": 5851 }, {
  "UrlFacet": "nam-dinh",
  "Title": "Nam Định",
  "Total": 12144
}, { "UrlFacet": "nghe-an", "Title": "Nghệ An", "Total": 23232 }, {
  "UrlFacet": "ninh-binh",
  "Title": "Ninh Bình",
  "Total": 8021
}, { "UrlFacet": "ninh-thuan", "Title": "Ninh Thuận", "Total": 4919 }, {
  "UrlFacet": "phu-tho",
  "Title": "Phú Thọ",
  "Total": 9905
}, { "UrlFacet": "phu-yen", "Title": "Phú Yên", "Total": 6580 }, {
  "UrlFacet": "quang-binh",
  "Title": "Quảng Bình",
  "Total": 8540
}, { "UrlFacet": "quang-nam", "Title": "Quảng Nam", "Total": 14115 }, {
  "UrlFacet": "quang-ngai",
  "Title": "Quảng Ngãi",
  "Total": 10422
}, { "UrlFacet": "quang-ninh", "Title": "Quảng Ninh", "Total": 19784 }, {
  "UrlFacet": "quang-tri",
  "Title": "Quảng Trị",
  "Total": 7041
}, { "UrlFacet": "soc-trang", "Title": "Sóc Trăng", "Total": 6441 }, {
  "UrlFacet": "son-la",
  "Title": "Sơn La",
  "Total": 5408
}, { "UrlFacet": "tp-ho-chi-minh", "Title": "TP Hồ Chí Minh", "Total": 463484 }, {
  "UrlFacet": "thanh-hoa",
  "Title": "Thanh Hoá",
  "Total": 24742
}, { "UrlFacet": "thai-binh", "Title": "Thái Bình", "Total": 10979 }, {
  "UrlFacet": "thai-nguyen",
  "Title": "Thái Nguyên",
  "Total": 9749
}, { "UrlFacet": "tien-giang", "Title": "Tiền Giang", "Total": 10774 }, {
  "UrlFacet": "tra-vinh",
  "Title": "Trà Vinh",
  "Total": 5652
}, { "UrlFacet": "tuyen-quang", "Title": "Tuyên Quang", "Total": 3763 }, {
  "UrlFacet": "tay-ninh",
  "Title": "Tây Ninh",
  "Total": 11313
}, { "UrlFacet": "vinh-long", "Title": "Vĩnh Long", "Total": 7261 }, {
  "UrlFacet": "vinh-phuc",
  "Title": "Vĩnh Phúc",
  "Total": 13031
}, { "UrlFacet": "vung-tau", "Title": "Vũng Tàu", "Total": 18479 }, {
  "UrlFacet": "yen-bai",
  "Title": "Yên Bái",
  "Total": 4972
}, { "UrlFacet": "dien-bien", "Title": "Điện Biên", "Total": 3194 }, {
  "UrlFacet": "da-nang",
  "Title": "Đà Nẵng",
  "Total": 40808
}, { "UrlFacet": "dac-lac", "Title": "Đắc Lắc", "Total": 11098 }, {
  "UrlFacet": "dak-nong",
  "Title": "Đắk Nông",
  "Total": 5411
}, { "UrlFacet": "dong-nai", "Title": "Đồng Nai", "Total": 42068 }, {
  "UrlFacet": "dong-thap",
  "Title": "Đồng Tháp",
  "Total": 10543
}];

// Doanh nghiệp mới thành lập

const data2 = [{
  "Type": 11,
  "SolrID": "/0316957067-cong-ty-tnhh-xuat-nhap-khau-quynh-my-food",
  "ID": 0,
  "MaSoThue": "0316957067",
  "NgayCap": "2021-09-09T00:00:00Z",
  "NgayDongMST": null,
  "Title": "Công Ty TNHH Xuất Nhập Khẩu Quỳnh My Food",
  "TitleEn": null,
  "TitleEnAscii": null,
  "DiaChiCongTy": "80/28/10 Dương Quảng Hàm, Phường 5, Quận Gò Vấp, Thành phố Hồ Chí Minh",
  "DiaChiNhanThongBaoThue": null,
  "NamTaiChinh": null,
  "MaSoHienThoi": null,
  "NgayNhanToKhai": null,
  "NgayBatDauHopDong": null,
  "VonDieuLe": null,
  "TongSoLaoDong": null,
  "CapChuongLoaiKhoan": null,
  "HinhThucThanhToan": null,
  "PhuongPhapTinhThueGTGT": null,
  "ChuSoHuu": null,
  "ChuSoHuu_DiaChi": null,
  "GiamDoc": null,
  "GiamDoc_DiaChi": null,
  "KeToanTruong": null,
  "KeToanTruong_DiaChi": null,
  "Created": "2021-09-09T07:35:32Z",
  "Updated": "2021-09-09T07:35:32Z",
  "IsDelete": false,
  "RequestChanged": false,
  "ExitsInGDT": false,
  "SourceID": 0,
  "TinhThanhID": 0,
  "TinhThanhTitle": "TP Hồ Chí Minh",
  "TinhThanhTitleAscii": "/tp-ho-chi-minh",
  "QuanHuyenID": 0,
  "QuanHuyenTitle": null,
  "QuanHuyenTitleAscii": null,
  "PhuongXaID": null,
  "PhuongXaTitle": null,
  "PhuongXaTitleAscii": null,
  "NoiDangKyQuanLyID": null,
  "NoiDangKyQuanLy_CoQuanTitle": null,
  "NoiDangKyQuanLy_CoQuanTitleAscii": null,
  "NoiDangKyQuanLy_DienThoai": null,
  "NoiDangKyQuanLy_Fax": null,
  "NoiNopThueID": null,
  "NoiNopThue_DienThoai": null,
  "NoiNopThue_Fax": null,
  "NoiNopThue_CoQuanTitle": null,
  "NoiNopThue_CoQuanTitleAscii": null,
  "QuyetDinhThanhLap": null,
  "QuyetDinhThanhLap_NgayCap": null,
  "QuyetDinhThanhLap_CoQuanCapID": null,
  "QuyetDinhThanhLap_CoQuanCapTitle": null,
  "QuyetDinhThanhLap_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh_CoQuanCapID": null,
  "GiayPhepKinhDoanh_CoQuanCapTitle": null,
  "GiayPhepKinhDoanh_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh": null,
  "GiayPhepKinhDoanh_NgayCap": null,
  "LoaiHinhID": null,
  "LoaiHinhTitle": null,
  "LoaiHinhTitleAscii": null,
  "NganhNgheID": null,
  "NganhNgheTitle": "Bán buôn thực phẩm",
  "NganhNgheTitleAscii": "/nganh-nghe/ban-buon-thuc-pham",
  "DSNganhNgheKinhDoanh": [],
  "DSNganhNgheKinhDoanhID": [],
  "DSMaNganhNgheKinhDoanh": [],
  "Lv1": null,
  "Lv2": null,
  "Lv3": null,
  "Lv4": null,
  "Lv5": null,
  "DSNganHang": [],
  "DSNganHangID": [],
  "DSThuePhaiNop": [],
  "DSThuePhaiNopID": [],
  "LtsDoanhNghiepTrucThuoc": [],
  "DSTags": ["0316957067", "TP Hồ Chí Minh", null]
}, {
  "Type": 11,
  "SolrID": "/0316957081-cong-ty-co-phan-thiet-ke-xay-dung-topazcons",
  "ID": 0,
  "MaSoThue": "0316957081",
  "NgayCap": "2021-09-09T00:00:00Z",
  "NgayDongMST": null,
  "Title": "Công Ty Cổ Phần Thiết Kế Xây Dựng Topazcons",
  "TitleEn": null,
  "TitleEnAscii": null,
  "DiaChiCongTy": "28/02 Đường 39, Khu phố 5, Phường Bình Trưng Đông, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
  "DiaChiNhanThongBaoThue": null,
  "NamTaiChinh": null,
  "MaSoHienThoi": null,
  "NgayNhanToKhai": null,
  "NgayBatDauHopDong": null,
  "VonDieuLe": null,
  "TongSoLaoDong": null,
  "CapChuongLoaiKhoan": null,
  "HinhThucThanhToan": null,
  "PhuongPhapTinhThueGTGT": null,
  "ChuSoHuu": null,
  "ChuSoHuu_DiaChi": null,
  "GiamDoc": null,
  "GiamDoc_DiaChi": null,
  "KeToanTruong": null,
  "KeToanTruong_DiaChi": null,
  "Created": "2021-09-09T07:35:35Z",
  "Updated": "2021-09-09T07:35:35Z",
  "IsDelete": false,
  "RequestChanged": false,
  "ExitsInGDT": false,
  "SourceID": 0,
  "TinhThanhID": 0,
  "TinhThanhTitle": "TP Hồ Chí Minh",
  "TinhThanhTitleAscii": "/tp-ho-chi-minh",
  "QuanHuyenID": 0,
  "QuanHuyenTitle": null,
  "QuanHuyenTitleAscii": null,
  "PhuongXaID": null,
  "PhuongXaTitle": null,
  "PhuongXaTitleAscii": null,
  "NoiDangKyQuanLyID": null,
  "NoiDangKyQuanLy_CoQuanTitle": null,
  "NoiDangKyQuanLy_CoQuanTitleAscii": null,
  "NoiDangKyQuanLy_DienThoai": null,
  "NoiDangKyQuanLy_Fax": null,
  "NoiNopThueID": null,
  "NoiNopThue_DienThoai": null,
  "NoiNopThue_Fax": null,
  "NoiNopThue_CoQuanTitle": null,
  "NoiNopThue_CoQuanTitleAscii": null,
  "QuyetDinhThanhLap": null,
  "QuyetDinhThanhLap_NgayCap": null,
  "QuyetDinhThanhLap_CoQuanCapID": null,
  "QuyetDinhThanhLap_CoQuanCapTitle": null,
  "QuyetDinhThanhLap_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh_CoQuanCapID": null,
  "GiayPhepKinhDoanh_CoQuanCapTitle": null,
  "GiayPhepKinhDoanh_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh": null,
  "GiayPhepKinhDoanh_NgayCap": null,
  "LoaiHinhID": null,
  "LoaiHinhTitle": null,
  "LoaiHinhTitleAscii": null,
  "NganhNgheID": null,
  "NganhNgheTitle": "",
  "NganhNgheTitleAscii": "",
  "DSNganhNgheKinhDoanh": [],
  "DSNganhNgheKinhDoanhID": [],
  "DSMaNganhNgheKinhDoanh": [],
  "Lv1": null,
  "Lv2": null,
  "Lv3": null,
  "Lv4": null,
  "Lv5": null,
  "DSNganHang": [],
  "DSNganHangID": [],
  "DSThuePhaiNop": [],
  "DSThuePhaiNopID": [],
  "LtsDoanhNghiepTrucThuoc": [],
  "DSTags": ["0316957081", "TP Hồ Chí Minh", null]
}, {
  "Type": 11,
  "SolrID": "/0316957074-cong-ty-tnhh-xuat-nhap-khau-thuc-pham-minh-hung",
  "ID": 0,
  "MaSoThue": "0316957074",
  "NgayCap": "2021-09-09T00:00:00Z",
  "NgayDongMST": null,
  "Title": "Công Ty TNHH Xuất Nhập Khẩu Thực Phẩm Minh Hưng",
  "TitleEn": null,
  "TitleEnAscii": null,
  "DiaChiCongTy": "647/24/2 Quốc lộ 13, Khu Phố 3, Phường Hiệp Bình Phước, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
  "DiaChiNhanThongBaoThue": null,
  "NamTaiChinh": null,
  "MaSoHienThoi": null,
  "NgayNhanToKhai": null,
  "NgayBatDauHopDong": null,
  "VonDieuLe": null,
  "TongSoLaoDong": null,
  "CapChuongLoaiKhoan": null,
  "HinhThucThanhToan": null,
  "PhuongPhapTinhThueGTGT": null,
  "ChuSoHuu": null,
  "ChuSoHuu_DiaChi": null,
  "GiamDoc": null,
  "GiamDoc_DiaChi": null,
  "KeToanTruong": null,
  "KeToanTruong_DiaChi": null,
  "Created": "2021-09-09T07:35:37Z",
  "Updated": "2021-09-09T07:35:37Z",
  "IsDelete": false,
  "RequestChanged": false,
  "ExitsInGDT": false,
  "SourceID": 0,
  "TinhThanhID": 0,
  "TinhThanhTitle": "TP Hồ Chí Minh",
  "TinhThanhTitleAscii": "/tp-ho-chi-minh",
  "QuanHuyenID": 0,
  "QuanHuyenTitle": null,
  "QuanHuyenTitleAscii": null,
  "PhuongXaID": null,
  "PhuongXaTitle": null,
  "PhuongXaTitleAscii": null,
  "NoiDangKyQuanLyID": null,
  "NoiDangKyQuanLy_CoQuanTitle": null,
  "NoiDangKyQuanLy_CoQuanTitleAscii": null,
  "NoiDangKyQuanLy_DienThoai": null,
  "NoiDangKyQuanLy_Fax": null,
  "NoiNopThueID": null,
  "NoiNopThue_DienThoai": null,
  "NoiNopThue_Fax": null,
  "NoiNopThue_CoQuanTitle": null,
  "NoiNopThue_CoQuanTitleAscii": null,
  "QuyetDinhThanhLap": null,
  "QuyetDinhThanhLap_NgayCap": null,
  "QuyetDinhThanhLap_CoQuanCapID": null,
  "QuyetDinhThanhLap_CoQuanCapTitle": null,
  "QuyetDinhThanhLap_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh_CoQuanCapID": null,
  "GiayPhepKinhDoanh_CoQuanCapTitle": null,
  "GiayPhepKinhDoanh_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh": null,
  "GiayPhepKinhDoanh_NgayCap": null,
  "LoaiHinhID": null,
  "LoaiHinhTitle": null,
  "LoaiHinhTitleAscii": null,
  "NganhNgheID": null,
  "NganhNgheTitle": "Bán buôn thực phẩm",
  "NganhNgheTitleAscii": "/nganh-nghe/ban-buon-thuc-pham",
  "DSNganhNgheKinhDoanh": [],
  "DSNganhNgheKinhDoanhID": [],
  "DSMaNganhNgheKinhDoanh": [],
  "Lv1": null,
  "Lv2": null,
  "Lv3": null,
  "Lv4": null,
  "Lv5": null,
  "DSNganHang": [],
  "DSNganHangID": [],
  "DSThuePhaiNop": [],
  "DSThuePhaiNopID": [],
  "LtsDoanhNghiepTrucThuoc": [],
  "DSTags": ["0316957074", "TP Hồ Chí Minh", null]
}, {
  "Type": 11,
  "SolrID": "/2700934104-cong-ty-tnhh-dau-tu-va-cong-nghe-i-house",
  "ID": 0,
  "MaSoThue": "2700934104",
  "NgayCap": "2021-09-08T00:00:00Z",
  "NgayDongMST": null,
  "Title": "Công Ty TNHH Đầu Tư Và Công Nghệ I House",
  "TitleEn": null,
  "TitleEnAscii": null,
  "DiaChiCongTy": "Số 4, ngõ 171, đường Nam Thành, Phường Phúc Thành, Thành phố Ninh Bình, Tỉnh Ninh Bình",
  "DiaChiNhanThongBaoThue": null,
  "NamTaiChinh": null,
  "MaSoHienThoi": null,
  "NgayNhanToKhai": null,
  "NgayBatDauHopDong": null,
  "VonDieuLe": null,
  "TongSoLaoDong": null,
  "CapChuongLoaiKhoan": null,
  "HinhThucThanhToan": null,
  "PhuongPhapTinhThueGTGT": null,
  "ChuSoHuu": null,
  "ChuSoHuu_DiaChi": null,
  "GiamDoc": null,
  "GiamDoc_DiaChi": null,
  "KeToanTruong": null,
  "KeToanTruong_DiaChi": null,
  "Created": "2021-09-08T09:35:32Z",
  "Updated": "2021-09-08T09:35:32Z",
  "IsDelete": false,
  "RequestChanged": false,
  "ExitsInGDT": false,
  "SourceID": 0,
  "TinhThanhID": 0,
  "TinhThanhTitle": "Ninh Bình",
  "TinhThanhTitleAscii": "/ninh-binh",
  "QuanHuyenID": 0,
  "QuanHuyenTitle": null,
  "QuanHuyenTitleAscii": null,
  "PhuongXaID": null,
  "PhuongXaTitle": null,
  "PhuongXaTitleAscii": null,
  "NoiDangKyQuanLyID": null,
  "NoiDangKyQuanLy_CoQuanTitle": null,
  "NoiDangKyQuanLy_CoQuanTitleAscii": null,
  "NoiDangKyQuanLy_DienThoai": null,
  "NoiDangKyQuanLy_Fax": null,
  "NoiNopThueID": null,
  "NoiNopThue_DienThoai": null,
  "NoiNopThue_Fax": null,
  "NoiNopThue_CoQuanTitle": null,
  "NoiNopThue_CoQuanTitleAscii": null,
  "QuyetDinhThanhLap": null,
  "QuyetDinhThanhLap_NgayCap": null,
  "QuyetDinhThanhLap_CoQuanCapID": null,
  "QuyetDinhThanhLap_CoQuanCapTitle": null,
  "QuyetDinhThanhLap_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh_CoQuanCapID": null,
  "GiayPhepKinhDoanh_CoQuanCapTitle": null,
  "GiayPhepKinhDoanh_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh": null,
  "GiayPhepKinhDoanh_NgayCap": null,
  "LoaiHinhID": null,
  "LoaiHinhTitle": null,
  "LoaiHinhTitleAscii": null,
  "NganhNgheID": null,
  "NganhNgheTitle": "Gia công cơ khí; xử lý và tráng phủ kim loại",
  "NganhNgheTitleAscii": "/nganh-nghe/gia-cong-co-khi-xu-ly-va-trang-phu-kim-loai",
  "DSNganhNgheKinhDoanh": [],
  "DSNganhNgheKinhDoanhID": [],
  "DSMaNganhNgheKinhDoanh": [],
  "Lv1": null,
  "Lv2": null,
  "Lv3": null,
  "Lv4": null,
  "Lv5": null,
  "DSNganHang": [],
  "DSNganHangID": [],
  "DSThuePhaiNop": [],
  "DSThuePhaiNopID": [],
  "LtsDoanhNghiepTrucThuoc": [],
  "DSTags": ["2700934104", "Ninh Bình", null]
}, {
  "Type": 11,
  "SolrID": "/0901107654-cong-ty-tnhh-van-chuyen-cap-cuu-115-hai-long",
  "ID": 0,
  "MaSoThue": "0901107654",
  "NgayCap": "2021-09-08T00:00:00Z",
  "NgayDongMST": null,
  "Title": "Công Ty TNHH Vận Chuyển Cấp Cứu 115 Hải Long",
  "TitleEn": null,
  "TitleEnAscii": null,
  "DiaChiCongTy": "Khu tái định cư Trạm y tế xã Trung Nghĩa, thôn Đào Đặng, Xã Trung Nghĩa, Thành phố Hưng yên, Tỉnh Hưng Yên",
  "DiaChiNhanThongBaoThue": null,
  "NamTaiChinh": null,
  "MaSoHienThoi": null,
  "NgayNhanToKhai": null,
  "NgayBatDauHopDong": null,
  "VonDieuLe": null,
  "TongSoLaoDong": null,
  "CapChuongLoaiKhoan": null,
  "HinhThucThanhToan": null,
  "PhuongPhapTinhThueGTGT": null,
  "ChuSoHuu": null,
  "ChuSoHuu_DiaChi": null,
  "GiamDoc": null,
  "GiamDoc_DiaChi": null,
  "KeToanTruong": null,
  "KeToanTruong_DiaChi": null,
  "Created": "2021-09-08T09:35:37Z",
  "Updated": "2021-09-08T09:35:37Z",
  "IsDelete": false,
  "RequestChanged": false,
  "ExitsInGDT": false,
  "SourceID": 0,
  "TinhThanhID": 0,
  "TinhThanhTitle": "Hưng Yên",
  "TinhThanhTitleAscii": "/hung-yen",
  "QuanHuyenID": 0,
  "QuanHuyenTitle": null,
  "QuanHuyenTitleAscii": null,
  "PhuongXaID": null,
  "PhuongXaTitle": null,
  "PhuongXaTitleAscii": null,
  "NoiDangKyQuanLyID": null,
  "NoiDangKyQuanLy_CoQuanTitle": null,
  "NoiDangKyQuanLy_CoQuanTitleAscii": null,
  "NoiDangKyQuanLy_DienThoai": null,
  "NoiDangKyQuanLy_Fax": null,
  "NoiNopThueID": null,
  "NoiNopThue_DienThoai": null,
  "NoiNopThue_Fax": null,
  "NoiNopThue_CoQuanTitle": null,
  "NoiNopThue_CoQuanTitleAscii": null,
  "QuyetDinhThanhLap": null,
  "QuyetDinhThanhLap_NgayCap": null,
  "QuyetDinhThanhLap_CoQuanCapID": null,
  "QuyetDinhThanhLap_CoQuanCapTitle": null,
  "QuyetDinhThanhLap_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh_CoQuanCapID": null,
  "GiayPhepKinhDoanh_CoQuanCapTitle": null,
  "GiayPhepKinhDoanh_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh": null,
  "GiayPhepKinhDoanh_NgayCap": null,
  "LoaiHinhID": null,
  "LoaiHinhTitle": null,
  "LoaiHinhTitleAscii": null,
  "NganhNgheID": null,
  "NganhNgheTitle": "Hoạt động y tế khác chưa được phân vào đâu",
  "NganhNgheTitleAscii": "/nganh-nghe/hoat-dong-y-te-khac-chua-duoc-phan-vao-dau",
  "DSNganhNgheKinhDoanh": [],
  "DSNganhNgheKinhDoanhID": [],
  "DSMaNganhNgheKinhDoanh": [],
  "Lv1": null,
  "Lv2": null,
  "Lv3": null,
  "Lv4": null,
  "Lv5": null,
  "DSNganHang": [],
  "DSNganHangID": [],
  "DSThuePhaiNop": [],
  "DSThuePhaiNopID": [],
  "LtsDoanhNghiepTrucThuoc": [],
  "DSTags": ["0901107654", "Hưng Yên", null]
}, {
  "Type": 11,
  "SolrID": "/0202121536-cong-ty-tnhh-dich-vu-va-giao-duc-ha-le",
  "ID": 0,
  "MaSoThue": "0202121536",
  "NgayCap": "2021-09-08T00:00:00Z",
  "NgayDongMST": null,
  "Title": "Công Ty TNHH  Dịch Vụ Và Giáo Dục Hà Lê",
  "TitleEn": null,
  "TitleEnAscii": null,
  "DiaChiCongTy": "Số 36/45 Tô Vũ, Phường Đằng Lâm, Quận Hải An, Thành phố Hải Phòng",
  "DiaChiNhanThongBaoThue": null,
  "NamTaiChinh": null,
  "MaSoHienThoi": null,
  "NgayNhanToKhai": null,
  "NgayBatDauHopDong": null,
  "VonDieuLe": null,
  "TongSoLaoDong": null,
  "CapChuongLoaiKhoan": null,
  "HinhThucThanhToan": null,
  "PhuongPhapTinhThueGTGT": null,
  "ChuSoHuu": null,
  "ChuSoHuu_DiaChi": null,
  "GiamDoc": null,
  "GiamDoc_DiaChi": null,
  "KeToanTruong": null,
  "KeToanTruong_DiaChi": null,
  "Created": "2021-09-08T09:35:40Z",
  "Updated": "2021-09-08T09:35:40Z",
  "IsDelete": false,
  "RequestChanged": false,
  "ExitsInGDT": false,
  "SourceID": 0,
  "TinhThanhID": 0,
  "TinhThanhTitle": "Hải Phòng",
  "TinhThanhTitleAscii": "/hai-phong",
  "QuanHuyenID": 0,
  "QuanHuyenTitle": null,
  "QuanHuyenTitleAscii": null,
  "PhuongXaID": null,
  "PhuongXaTitle": null,
  "PhuongXaTitleAscii": null,
  "NoiDangKyQuanLyID": null,
  "NoiDangKyQuanLy_CoQuanTitle": null,
  "NoiDangKyQuanLy_CoQuanTitleAscii": null,
  "NoiDangKyQuanLy_DienThoai": null,
  "NoiDangKyQuanLy_Fax": null,
  "NoiNopThueID": null,
  "NoiNopThue_DienThoai": null,
  "NoiNopThue_Fax": null,
  "NoiNopThue_CoQuanTitle": null,
  "NoiNopThue_CoQuanTitleAscii": null,
  "QuyetDinhThanhLap": null,
  "QuyetDinhThanhLap_NgayCap": null,
  "QuyetDinhThanhLap_CoQuanCapID": null,
  "QuyetDinhThanhLap_CoQuanCapTitle": null,
  "QuyetDinhThanhLap_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh_CoQuanCapID": null,
  "GiayPhepKinhDoanh_CoQuanCapTitle": null,
  "GiayPhepKinhDoanh_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh": null,
  "GiayPhepKinhDoanh_NgayCap": null,
  "LoaiHinhID": null,
  "LoaiHinhTitle": null,
  "LoaiHinhTitleAscii": null,
  "NganhNgheID": null,
  "NganhNgheTitle": "Giáo dục khác chưa được phân vào đâu",
  "NganhNgheTitleAscii": "/nganh-nghe/giao-duc-khac-chua-duoc-phan-vao-dau",
  "DSNganhNgheKinhDoanh": [],
  "DSNganhNgheKinhDoanhID": [],
  "DSMaNganhNgheKinhDoanh": [],
  "Lv1": null,
  "Lv2": null,
  "Lv3": null,
  "Lv4": null,
  "Lv5": null,
  "DSNganHang": [],
  "DSNganHangID": [],
  "DSThuePhaiNop": [],
  "DSThuePhaiNopID": [],
  "LtsDoanhNghiepTrucThuoc": [],
  "DSTags": ["0202121536", "Hải Phòng", null]
}, {
  "Type": 11,
  "SolrID": "/0316956659-cong-ty-tnhh-adcity",
  "ID": 0,
  "MaSoThue": "0316956659",
  "NgayCap": "2021-09-08T00:00:00Z",
  "NgayDongMST": null,
  "Title": "Công Ty TNHH Adcity",
  "TitleEn": null,
  "TitleEnAscii": null,
  "DiaChiCongTy": "Tầng 3, Cao ốc Bảo Gia, 184 Lê Đại Hành, Phường 15, Quận 11, Thành phố Hồ Chí Minh",
  "DiaChiNhanThongBaoThue": null,
  "NamTaiChinh": null,
  "MaSoHienThoi": null,
  "NgayNhanToKhai": null,
  "NgayBatDauHopDong": null,
  "VonDieuLe": null,
  "TongSoLaoDong": null,
  "CapChuongLoaiKhoan": null,
  "HinhThucThanhToan": null,
  "PhuongPhapTinhThueGTGT": null,
  "ChuSoHuu": null,
  "ChuSoHuu_DiaChi": null,
  "GiamDoc": null,
  "GiamDoc_DiaChi": null,
  "KeToanTruong": null,
  "KeToanTruong_DiaChi": null,
  "Created": "2021-09-08T09:35:44Z",
  "Updated": "2021-09-08T09:35:44Z",
  "IsDelete": false,
  "RequestChanged": false,
  "ExitsInGDT": false,
  "SourceID": 0,
  "TinhThanhID": 0,
  "TinhThanhTitle": "TP Hồ Chí Minh",
  "TinhThanhTitleAscii": "/tp-ho-chi-minh",
  "QuanHuyenID": 0,
  "QuanHuyenTitle": null,
  "QuanHuyenTitleAscii": null,
  "PhuongXaID": null,
  "PhuongXaTitle": null,
  "PhuongXaTitleAscii": null,
  "NoiDangKyQuanLyID": null,
  "NoiDangKyQuanLy_CoQuanTitle": null,
  "NoiDangKyQuanLy_CoQuanTitleAscii": null,
  "NoiDangKyQuanLy_DienThoai": null,
  "NoiDangKyQuanLy_Fax": null,
  "NoiNopThueID": null,
  "NoiNopThue_DienThoai": null,
  "NoiNopThue_Fax": null,
  "NoiNopThue_CoQuanTitle": null,
  "NoiNopThue_CoQuanTitleAscii": null,
  "QuyetDinhThanhLap": null,
  "QuyetDinhThanhLap_NgayCap": null,
  "QuyetDinhThanhLap_CoQuanCapID": null,
  "QuyetDinhThanhLap_CoQuanCapTitle": null,
  "QuyetDinhThanhLap_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh_CoQuanCapID": null,
  "GiayPhepKinhDoanh_CoQuanCapTitle": null,
  "GiayPhepKinhDoanh_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh": null,
  "GiayPhepKinhDoanh_NgayCap": null,
  "LoaiHinhID": null,
  "LoaiHinhTitle": null,
  "LoaiHinhTitleAscii": null,
  "NganhNgheID": null,
  "NganhNgheTitle": "Quảng cáo",
  "NganhNgheTitleAscii": "/nganh-nghe/quang-cao",
  "DSNganhNgheKinhDoanh": [],
  "DSNganhNgheKinhDoanhID": [],
  "DSMaNganhNgheKinhDoanh": [],
  "Lv1": null,
  "Lv2": null,
  "Lv3": null,
  "Lv4": null,
  "Lv5": null,
  "DSNganHang": [],
  "DSNganHangID": [],
  "DSThuePhaiNop": [],
  "DSThuePhaiNopID": [],
  "LtsDoanhNghiepTrucThuoc": [],
  "DSTags": ["0316956659", "TP Hồ Chí Minh", null]
}, {
  "Type": 11,
  "SolrID": "/0801362636-cong-ty-co-phan-dvtm-thinh-an-phat",
  "ID": 0,
  "MaSoThue": "0801362636",
  "NgayCap": "2021-09-08T00:00:00Z",
  "NgayDongMST": null,
  "Title": "Công Ty Cổ Phần Dvtm Thịnh An Phát",
  "TitleEn": null,
  "TitleEnAscii": null,
  "DiaChiCongTy": "Thôn An Sơn, Xã Hồng Quang, Huyện Thanh Miện, Tỉnh Hải Dương",
  "DiaChiNhanThongBaoThue": null,
  "NamTaiChinh": null,
  "MaSoHienThoi": null,
  "NgayNhanToKhai": null,
  "NgayBatDauHopDong": null,
  "VonDieuLe": null,
  "TongSoLaoDong": null,
  "CapChuongLoaiKhoan": null,
  "HinhThucThanhToan": null,
  "PhuongPhapTinhThueGTGT": null,
  "ChuSoHuu": null,
  "ChuSoHuu_DiaChi": null,
  "GiamDoc": null,
  "GiamDoc_DiaChi": null,
  "KeToanTruong": null,
  "KeToanTruong_DiaChi": null,
  "Created": "2021-09-08T09:35:47Z",
  "Updated": "2021-09-08T09:35:47Z",
  "IsDelete": false,
  "RequestChanged": false,
  "ExitsInGDT": false,
  "SourceID": 0,
  "TinhThanhID": 0,
  "TinhThanhTitle": "Hải Dương",
  "TinhThanhTitleAscii": "/hai-duong",
  "QuanHuyenID": 0,
  "QuanHuyenTitle": null,
  "QuanHuyenTitleAscii": null,
  "PhuongXaID": null,
  "PhuongXaTitle": null,
  "PhuongXaTitleAscii": null,
  "NoiDangKyQuanLyID": null,
  "NoiDangKyQuanLy_CoQuanTitle": null,
  "NoiDangKyQuanLy_CoQuanTitleAscii": null,
  "NoiDangKyQuanLy_DienThoai": null,
  "NoiDangKyQuanLy_Fax": null,
  "NoiNopThueID": null,
  "NoiNopThue_DienThoai": null,
  "NoiNopThue_Fax": null,
  "NoiNopThue_CoQuanTitle": null,
  "NoiNopThue_CoQuanTitleAscii": null,
  "QuyetDinhThanhLap": null,
  "QuyetDinhThanhLap_NgayCap": null,
  "QuyetDinhThanhLap_CoQuanCapID": null,
  "QuyetDinhThanhLap_CoQuanCapTitle": null,
  "QuyetDinhThanhLap_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh_CoQuanCapID": null,
  "GiayPhepKinhDoanh_CoQuanCapTitle": null,
  "GiayPhepKinhDoanh_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh": null,
  "GiayPhepKinhDoanh_NgayCap": null,
  "LoaiHinhID": null,
  "LoaiHinhTitle": null,
  "LoaiHinhTitleAscii": null,
  "NganhNgheID": null,
  "NganhNgheTitle": "Kinh doanh bất động sản, quyền sử dụng đất thuộc chủ sở hữu, chủ sử dụng hoặc đi thuê",
  "NganhNgheTitleAscii": "/nganh-nghe/kinh-doanh-bat-dong-san-quyen-su-dung-dat-thuoc-chu-so-huu-chu-su-dung-hoac-di-thue",
  "DSNganhNgheKinhDoanh": [],
  "DSNganhNgheKinhDoanhID": [],
  "DSMaNganhNgheKinhDoanh": [],
  "Lv1": null,
  "Lv2": null,
  "Lv3": null,
  "Lv4": null,
  "Lv5": null,
  "DSNganHang": [],
  "DSNganHangID": [],
  "DSThuePhaiNop": [],
  "DSThuePhaiNopID": [],
  "LtsDoanhNghiepTrucThuoc": [],
  "DSTags": ["0801362636", "Hải Dương", null]
}, {
  "Type": 11,
  "SolrID": "/0316956715-cong-ty-tnhh-powermaps-tuning-llc",
  "ID": 0,
  "MaSoThue": "0316956715",
  "NgayCap": "2021-09-08T00:00:00Z",
  "NgayDongMST": null,
  "Title": "Công Ty TNHH Powermaps Tuning Llc",
  "TitleEn": null,
  "TitleEnAscii": null,
  "DiaChiCongTy": "243A/45 Hoàng Diệu, Phường 08, Quận 4, Thành phố Hồ Chí Minh",
  "DiaChiNhanThongBaoThue": null,
  "NamTaiChinh": null,
  "MaSoHienThoi": null,
  "NgayNhanToKhai": null,
  "NgayBatDauHopDong": null,
  "VonDieuLe": null,
  "TongSoLaoDong": null,
  "CapChuongLoaiKhoan": null,
  "HinhThucThanhToan": null,
  "PhuongPhapTinhThueGTGT": null,
  "ChuSoHuu": null,
  "ChuSoHuu_DiaChi": null,
  "GiamDoc": null,
  "GiamDoc_DiaChi": null,
  "KeToanTruong": null,
  "KeToanTruong_DiaChi": null,
  "Created": "2021-09-08T09:35:50Z",
  "Updated": "2021-09-08T09:35:50Z",
  "IsDelete": false,
  "RequestChanged": false,
  "ExitsInGDT": false,
  "SourceID": 0,
  "TinhThanhID": 0,
  "TinhThanhTitle": "TP Hồ Chí Minh",
  "TinhThanhTitleAscii": "/tp-ho-chi-minh",
  "QuanHuyenID": 0,
  "QuanHuyenTitle": null,
  "QuanHuyenTitleAscii": null,
  "PhuongXaID": null,
  "PhuongXaTitle": null,
  "PhuongXaTitleAscii": null,
  "NoiDangKyQuanLyID": null,
  "NoiDangKyQuanLy_CoQuanTitle": null,
  "NoiDangKyQuanLy_CoQuanTitleAscii": null,
  "NoiDangKyQuanLy_DienThoai": null,
  "NoiDangKyQuanLy_Fax": null,
  "NoiNopThueID": null,
  "NoiNopThue_DienThoai": null,
  "NoiNopThue_Fax": null,
  "NoiNopThue_CoQuanTitle": null,
  "NoiNopThue_CoQuanTitleAscii": null,
  "QuyetDinhThanhLap": null,
  "QuyetDinhThanhLap_NgayCap": null,
  "QuyetDinhThanhLap_CoQuanCapID": null,
  "QuyetDinhThanhLap_CoQuanCapTitle": null,
  "QuyetDinhThanhLap_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh_CoQuanCapID": null,
  "GiayPhepKinhDoanh_CoQuanCapTitle": null,
  "GiayPhepKinhDoanh_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh": null,
  "GiayPhepKinhDoanh_NgayCap": null,
  "LoaiHinhID": null,
  "LoaiHinhTitle": null,
  "LoaiHinhTitleAscii": null,
  "NganhNgheID": null,
  "NganhNgheTitle": "Bảo dưỡng, sửa chữa ô tô và xe có động cơ khác",
  "NganhNgheTitleAscii": "/nganh-nghe/bao-duong-sua-chua-o-to-va-xe-co-dong-co-khac",
  "DSNganhNgheKinhDoanh": [],
  "DSNganhNgheKinhDoanhID": [],
  "DSMaNganhNgheKinhDoanh": [],
  "Lv1": null,
  "Lv2": null,
  "Lv3": null,
  "Lv4": null,
  "Lv5": null,
  "DSNganHang": [],
  "DSNganHangID": [],
  "DSThuePhaiNop": [],
  "DSThuePhaiNopID": [],
  "LtsDoanhNghiepTrucThuoc": [],
  "DSTags": ["0316956715", "TP Hồ Chí Minh", null]
}, {
  "Type": 11,
  "SolrID": "/0316956722-cong-ty-tnhh-tu-van-novel-life",
  "ID": 0,
  "MaSoThue": "0316956722",
  "NgayCap": "2021-09-08T00:00:00Z",
  "NgayDongMST": null,
  "Title": "Công Ty TNHH Tư Vấn Novel Life",
  "TitleEn": null,
  "TitleEnAscii": null,
  "DiaChiCongTy": "316 Lê Văn Sỹ, Phường 1, Quận Tân Bình, Thành phố Hồ Chí Minh",
  "DiaChiNhanThongBaoThue": null,
  "NamTaiChinh": null,
  "MaSoHienThoi": null,
  "NgayNhanToKhai": null,
  "NgayBatDauHopDong": null,
  "VonDieuLe": null,
  "TongSoLaoDong": null,
  "CapChuongLoaiKhoan": null,
  "HinhThucThanhToan": null,
  "PhuongPhapTinhThueGTGT": null,
  "ChuSoHuu": null,
  "ChuSoHuu_DiaChi": null,
  "GiamDoc": null,
  "GiamDoc_DiaChi": null,
  "KeToanTruong": null,
  "KeToanTruong_DiaChi": null,
  "Created": "2021-09-08T09:35:53Z",
  "Updated": "2021-09-08T09:35:53Z",
  "IsDelete": false,
  "RequestChanged": false,
  "ExitsInGDT": false,
  "SourceID": 0,
  "TinhThanhID": 0,
  "TinhThanhTitle": "TP Hồ Chí Minh",
  "TinhThanhTitleAscii": "/tp-ho-chi-minh",
  "QuanHuyenID": 0,
  "QuanHuyenTitle": null,
  "QuanHuyenTitleAscii": null,
  "PhuongXaID": null,
  "PhuongXaTitle": null,
  "PhuongXaTitleAscii": null,
  "NoiDangKyQuanLyID": null,
  "NoiDangKyQuanLy_CoQuanTitle": null,
  "NoiDangKyQuanLy_CoQuanTitleAscii": null,
  "NoiDangKyQuanLy_DienThoai": null,
  "NoiDangKyQuanLy_Fax": null,
  "NoiNopThueID": null,
  "NoiNopThue_DienThoai": null,
  "NoiNopThue_Fax": null,
  "NoiNopThue_CoQuanTitle": null,
  "NoiNopThue_CoQuanTitleAscii": null,
  "QuyetDinhThanhLap": null,
  "QuyetDinhThanhLap_NgayCap": null,
  "QuyetDinhThanhLap_CoQuanCapID": null,
  "QuyetDinhThanhLap_CoQuanCapTitle": null,
  "QuyetDinhThanhLap_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh_CoQuanCapID": null,
  "GiayPhepKinhDoanh_CoQuanCapTitle": null,
  "GiayPhepKinhDoanh_CoQuanCapTitleAscii": null,
  "GiayPhepKinhDoanh": null,
  "GiayPhepKinhDoanh_NgayCap": null,
  "LoaiHinhID": null,
  "LoaiHinhTitle": null,
  "LoaiHinhTitleAscii": null,
  "NganhNgheID": null,
  "NganhNgheTitle": "Dịch vụ hỗ trợ giáo dục",
  "NganhNgheTitleAscii": "/nganh-nghe/dich-vu-ho-tro-giao-duc",
  "DSNganhNgheKinhDoanh": [],
  "DSNganhNgheKinhDoanhID": [],
  "DSMaNganhNgheKinhDoanh": [],
  "Lv1": null,
  "Lv2": null,
  "Lv3": null,
  "Lv4": null,
  "Lv5": null,
  "DSNganHang": [],
  "DSNganHangID": [],
  "DSThuePhaiNop": [],
  "DSThuePhaiNopID": [],
  "LtsDoanhNghiepTrucThuoc": [],
  "DSTags": ["0316956722", "TP Hồ Chí Minh", null]
}];
